services:
  postgres:
    image: "postgres:14"

    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql